DROP TABLE IF EXISTS knownForTitles;

DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS primaryProfession;

DROP TABLE IF EXISTS genreId;
DROP TABLE IF EXISTS primaryProfessionID;

DROP TABLE IF EXISTS titleRatings;
DROP TABLE IF EXISTS titlePrincipals;
DROP TABLE IF EXISTS nameBasics;
DROP TABLE IF EXISTS titleBasics;
